{% set version = "0.3.4" %}

package:
  name: glog
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/google/glog/archive/v{{ version }}.tar.gz
  sha1: 69f91cd5a1de35ead0bc4103ea87294b0206a456
  patches:
    - glog_b6a5e0524c28178985f0d228e9eaa43808dbec3c.patch  # [win]
build:
  number: 1
  features:
    - vc9  # [win and py27]
    - vc10 # [win and py34]
    - vc14 # [win and py35]

requirements:
  build:
    - autoconf  # [not win]
    - automake  # [not win]
    - libtool   # [not win]
    - cmake     # [win]
    - gflags    # [win]

test:
  commands:
    - exit $(test -f ${PREFIX}/lib/libglog.dylib)            # [osx]
    - exit $(test -f ${PREFIX}/lib/libglog_nothreads.dylib)  # [osx]
    - exit $(test -f ${PREFIX}/lib/libglog.so)               # [linux]
    - exit $(test -f ${PREFIX}/lib/libglog_nothreads.so)     # [linux]

about:
  home: https://github.com/google/glog
  license: BSD
  summary: C++ implementation of the Google logging module.

extra:
  recipe-maintainers:
    - jakirkham
